/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BrainDumpRouteImport } from './routes/brain-dump'
import { Route as AllRouteImport } from './routes/all'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainDumpRoute = BrainDumpRouteImport.update({
  id: '/brain-dump',
  path: '/brain-dump',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/brain-dump': typeof BrainDumpRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/brain-dump': typeof BrainDumpRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/brain-dump': typeof BrainDumpRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/all' | '/brain-dump' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all' | '/brain-dump' | '/settings'
  id: '__root__' | '/' | '/all' | '/brain-dump' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRoute: typeof AllRoute
  BrainDumpRoute: typeof BrainDumpRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain-dump': {
      id: '/brain-dump'
      path: '/brain-dump'
      fullPath: '/brain-dump'
      preLoaderRoute: typeof BrainDumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRoute: AllRoute,
  BrainDumpRoute: BrainDumpRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
